---

- name: Install | Install telegraf packages
  when: telegraf_use_docker | lower == 'false'
  package:
    name: "{{ telegraf_distro_packages }}"
    state: "{{ telegraf_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags:
    - install-apt
    - install-yum
    - install-zypper

- name: Install | Pull docker image
  when: telegraf_use_docker | lower == 'true'
  docker_image:
    name: "{{ telegraf_docker_image }}"
    tag: "{{ telegraf_docker_tag }}"
  register: pull_docker
  until: pull_docker is success
  retries: 5
  delay: 60
  tags:
    - pull-docker
