- name: Converge
  hosts: all
  tasks:
  - name: Include ../../..
    include_role:
      name: ../../..
  vars:
    telegraf_http_proxy: "{{ lookup('env','http_proxy') }}"
    telegraf_https_proxy: "{{ lookup('env','https_proxy') }}"
    telegraf_http_no_proxy: "{{ lookup('env','no_proxy') }}"
    telegraf_output_influxdbv2_config:
      urls: [http://localhost:8086]
      token: secret
      org: my-org
      bucket: default
      bucket_tag: ''
      exclude_bucket_tag: false
      insecure_skip_verify: false
